window.SAMPLES = window.SAMPLES || {};
window.SAMPLES['lg_trip'] = [
    " Trip Planner Agent",
    "==================================================",
    "Type your travel request. Type 'quit' to exit.",
    "",
    "You: Find flights from Delhi to Tokyo in June 2026",
    "",
    "Agent: I'd be happy to help you find flights from Delhi to Tokyo in June 2026! However, I need a specific date to search for flights. June 2026 covers many possible dates.",
    "",
    "Could you please provide:",
    "- The specific date you'd like to travel (e.g., \"2026-06-15\")",
    "",
    "Once you give me the exact date, I'll search for available flights from Delhi to Tokyo for you.",
    "",
    "You: June 29th , 2025",
    "  🔧 mock_search_flights({'origin': 'Delhi', 'destination': 'Tokyo', 'date': '2025-06-29'})",
    "",
    "Agent: Here are the available flights from Delhi to Tokyo on June 29th, 2025:",
    "",
    "## Flight Options:",
    "",
    "**1. Air India AI-307** - Direct Flight",
    "- Departure: 08:30 from Delhi",
    "- Arrival: 22:45 same day in Tokyo",
    "- Price: ₹45,000",
    "",
    "**2. JAL JL-752** - Direct Flight",
    "- Departure: 14:20 from Delhi",
    "- Arrival: 05:30 next day in Tokyo",
    "- Price: ₹52,000",
    "",
    "**3. IndiGo 6E-4521** - One Stop",
    "- Departure: 06:00 from Delhi",
    "- Arrival: 18:30 same day in Tokyo",
    "- Price: ₹38,000",
    "- One stop in Bangkok (most economical option)",
    "",
    "Would you like me to also search for hotels in Tokyo for your stay?",
    "",
    "You: 3",
    "",
    "Agent: Great choice! The IndiGo 6E-4521 flight is the most economical option at ₹38,000 with a stop in Bangkok.",
    "",
    "To proceed with booking this flight, I'll need your full name as it appears on your passport.",
    "",
    "You: Kiran K Saravana",
    "  🔧 mock_book_flight({'flight_id': '6E-4521', 'passenger_name': 'Kiran K Saravana'})",
    "",
    "Agent: ## ✅ Flight Booking Confirmed!",
    "",
    "- **Flight:** IndiGo 6E-4521",
    "- **Passenger:** Kiran K Saravana",
    "- **Route:** Delhi → Tokyo (via Bangkok)",
    "- **Date:** June 29th, 2025",
    "- **Confirmation Code:** TRP02001",
    "",
    "Would you like me to search for hotels in Tokyo for your stay?",
    "",
    "You: yes , check in date June 29, 2026,  checkout date 5th July 2026,  budget = 10000/-",
    "",
    "Agent: I notice there's a date mismatch here. Your flight is booked for June 29th, **2025**, but you mentioned hotel check-in for June 29th, **2026**.",
    "",
    "Could you please clarify the correct year?",
    "",
    "You: for June 29th, 2025 to July 5th, 2025 (matching your flight dates)?",
    "  🔧 mock_search_hotels({'city': 'Tokyo', 'check_in': '2025-06-29', 'check_out': '2025-07-05', 'budget_inr': 10000})",
    "",
    "Agent: Here are the available hotels in Tokyo (June 29 - July 5, 2025):",
    "",
    "**1. Shinjuku Granbell Hotel** - 4★ — ₹8,500/night (₹51,000 total)",
    "**2. Dormy Inn Asakusa** - 3★ — ₹6,200/night (₹37,200 total, most economical!)",
    "**3. Citadines Shinjuku** - 4★ — ₹11,000/night (₹66,000 total, slightly over budget)",
    "",
    "You: 3",
    "",
    "Agent: I should mention that the Citadines Shinjuku is slightly over your stated budget of ₹10,000 per night at ₹11,000 per night. Are you okay with this price increase?",
    "",
    "You: date is wrong year is 2026",
    "  🔧 mock_search_flights({'origin': 'Delhi', 'destination': 'Tokyo', 'date': '2026-06-29'})",
    "  🔧 mock_search_hotels({'city': 'Tokyo', 'check_in': '2026-06-29', 'check_out': '2026-07-05', 'budget_inr': 10000})",
    "",
    "Agent: Perfect! Here are your options for **2026**:",
    "",
    "Since you chose option 3 for the hotel (Citadines Shinjuku at ₹11,000/night), and you previously chose the IndiGo flight, shall I proceed to book:",
    "- **Flight:** IndiGo 6E-4521 (₹38,000)",
    "- **Hotel:** Citadines Shinjuku (₹66,000 for 6 nights)",
    "",
    "You: yes",
    "  🔧 mock_book_flight({'flight_id': '6E-4521', 'passenger_name': 'Kiran K Saravana'})",
    "  🔧 mock_book_hotel({'hotel_name': 'Citadines Shinjuku', 'guest_name': 'Kiran K Saravana', 'check_in': '2026-06-29', 'check_out': '2026-07-05'})",
    "",
    "Agent: ## ✅ Complete Trip Booking Confirmed!",
    "",
    "**FLIGHT:** IndiGo 6E-4521 | Delhi → Tokyo (via Bangkok) | June 29, 2026 | ₹38,000 | Ref: TRP02001",
    "**HOTEL:** Citadines Shinjuku (4★) | June 29 - July 5, 2026 | 6 nights | ₹66,000 | Ref: HTL85847",
    "",
    "**TOTAL TRIP COST: ₹1,04,000**",
    "",
    "Have a wonderful trip to Tokyo, Kiran!",
].join("\n");
