window.SAMPLES = window.SAMPLES || {};
window.SAMPLES['lg_trip'] = [
    "🌍 Trip Planner Agent",
    "==================================================",
    "Type your travel request. Type 'quit' to exit.",
    "",
    "You: Find flights and hotels from Delhi to Tokyo in June 2025",
    "  🔧 mock_search_flights({'origin': 'Delhi', 'destination': 'Tokyo', 'date': '2025-06-15'})",
    "  🔧 mock_search_hotels({'city': 'Tokyo', 'check_in': '2025-06-15', 'check_out': '2025-06-20', 'budget_inr': 12000})",
    "",
    "Agent: Here are the best options I found:",
    "",
    "**Flights Delhi → Tokyo:**",
    "  1. IndiGo 6E-4521  ₹38,000  1-stop (Bangkok)",
    "  2. Air India AI-307  ₹45,000  Direct",
    "  3. JAL JL-752  ₹52,000  Direct",
    "",
    "**Hotels in Tokyo:**",
    "  1. Dormy Inn Asakusa  ₹6,200/night  3★  Traditional + onsen",
    "  2. Shinjuku Granbell  ₹8,500/night  4★  Near metro",
    "  3. Citadines Shinjuku  ₹11,000/night  4★  Serviced apt",
    "",
    "Shall I proceed to book IndiGo 6E-4521 + Dormy Inn Asakusa?",
    "",
    "You: yes book it",
    "",
    "⏸️  BOOKING APPROVAL REQUIRED",
    "-----------------------------------",
    "  Action: mock_book_flight",
    "  flight_id: 6E-4521",
    "  passenger_name: Kiran Kumar",
    "-----------------------------------",
    "Approve booking? (y/n): y",
    "▶ Proceeding with booking...",
    "",
    "  🔧 mock_book_flight({'flight_id': '6E-4521', 'passenger_name': 'Kiran Kumar'})",
    "  🔧 mock_book_hotel({'hotel_name': 'Dormy Inn Asakusa', 'guest_name': 'Kiran Kumar', ...})",
    "",
    "Agent: ✅ Your trip is booked!",
    "",
    "  ✈️  Flight: IndiGo 6E-4521 — Ref: TRP06234",
    "  🏨  Hotel: Dormy Inn Asakusa — Ref: HTL52814",
    "",
    "Safe travels! 🗾",
    "",
    "You: quit",
].join("\n");
